onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/TX
add wave -noupdate /main/RX
add wave -noupdate /main/CS
add wave -noupdate /main/SCL
add wave -noupdate /main/SDA
add wave -noupdate /main/SDO
add wave -noupdate /main/nReset
add wave -noupdate /main/Clk
add wave -noupdate /main/SendTX
add wave -noupdate /main/DataToSend
add wave -noupdate /main/DataFromRx
add wave -noupdate /main/TXisActive
add wave -noupdate /main/TXisDone
add wave -noupdate /main/RXAck
add wave -noupdate /main/RXDR
add wave -noupdate /main/RXA
add wave -noupdate /main/iTX
add wave -noupdate /main/count
add wave -noupdate /main/bit8SCLw
add wave -noupdate /main/bit8SDAw
add wave -noupdate /main/bit8SCLp
add wave -noupdate /main/bit8SDAp
add wave -noupdate /main/SDA_data
add wave -noupdate /main/SDA_datap
add wave -noupdate /main/SDO_datap
add wave -noupdate /main/DoneW
add wave -noupdate /main/DoneP
add wave -noupdate /main/csw
add wave -noupdate /main/csp
add wave -noupdate /main/iCSw
add wave -noupdate /main/iCSp
add wave -noupdate /main/SPI_R1W0
add wave -noupdate /main/Rdyp
add wave -noupdate /main/MISO_DR
add wave -noupdate /main/statedelay
add wave -noupdate /main/Asend
add wave -noupdate /main/Bsend
add wave -noupdate /main/State
add wave -noupdate /main/StateHolder
add wave -noupdate /main/U5/iCS
add wave -noupdate /main/U5/RW
add wave -noupdate /main/U5/Rdy
add wave -noupdate /main/U5/cs
add wave -noupdate /main/U5/Clk
add wave -noupdate /main/U5/from_SDO
add wave -noupdate /main/U5/Done
add wave -noupdate /main/U5/toSCL
add wave -noupdate /main/U5/toSDA
add wave -noupdate /main/U5/MISO_DR
add wave -noupdate /main/U5/next8bits
add wave -noupdate /main/U5/read8bits
add wave -noupdate /main/U5/CState
add wave -noupdate /main/U5/hold
add wave -noupdate /main/U5/RWlatch
add wave -noupdate /main/U5/BitIndex
add wave -noupdate /main/U5/ByteIndex
add wave -noupdate /main/U5/current8bits
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {35283738 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {3456484601 ps} {3534660002 ps}
